### ISSUE TITLE
Getting error when hitting Microsoft Teams option

### ISSUE THREAD

**Issue by gauravgoyal5** [mmsharepoint/ReactOutlook2SP_SPFx#1]
Hi, 
I am using following permission set in your example :
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Windows Azure Active Directory",
        "scope": "User.Read"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Files.Read"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Files.ReadWrite"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.ReadWrite"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Sites.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Teams.ReadBasic.All"
      }

But when I am clicking on "Microsoft Teams" option, it is throwing me an error :
![image](https://user-images.githubusercontent.com/6926513/83654396-ae109f80-a5da-11ea-9cb8-a557493904e7.png)

Can you please help me resolve this issue?

Thanks,
Gaurav

**Comment by mmsharepoint** [comment]
Sorry, I didn't try that again recently.
But did you check latest Microsoft Graph documentation?
As around last Build conference they were introducing lots of new and more granular permissions which might be a reason for this?

**Comment by mmsharepoint** [comment]
Just checked again and it's still running in my case.
Why did you use so much permissions? For instance I never granted "Teams.ReadBasic.All" in my tenant.
Group.Read.All is that one I only need to list Groups and Teams and this still works in my case

**Comment by gauravgoyal5** [comment]
Thanks for the reply. I was trying with the options. But it is not working for me. :(

**Comment by mmsharepoint** [comment]
You have to dig around a bit to get behind the scenes.
Does the Groups listing work in your case?
Did you check your tenant for the really consented permissions?
- On the one hand of course you approve them in Central Administration (or set via CLI / PowerShell directly?) 
- But did you also check the real app registration that Microsoft uses in that case? Go to your Azure AD App registrations and search for "SharePoint Online Client Extensibility Web Application Principal"?

Finally try the mentioned permissions in the documentation:
https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http 
I also have "Directory.Read.All" in my tenant due to another case which might do my difference?
"Group.Read.All" btw is not mentined in that document although I supposed to above ...

**Comment by gauravgoyal5** [comment]
Thanks for the suggestion .
I removed "Teams.ReadBasic.All" from SPFx. It is not working in one tenant but tried on another tenant, there it is working. :)

Thanks.
Gaurav Goyal
